## Jupyter Basic

    ### 제목을 클릭하면 파일 이름 변경 가능
    ### 셀을 누르고 a를 누르면, 위에 셀 추가
    ### 셀을 누르고 b를 누르면, 아래에 셀 추가
    ### 셀을 누르고 dd를 누르면, 해당 셀 삭제
    ### 이 외에도 잘라내기/복사/붙여넣기/이동 가능
    ### Shift를 누른 상태에서 드래그 가능
    ### 셀을 클릭 후 M을 누르면 Markdown으로 변환
    ### 다시 코드로 변경하려면 메인 위젯 아래의 오른쪽 2번째 리스트 박스 활용
    ### Ctrl + Enter를 누르면 실행
    ### Shift + Enter를 누르면 실행하며 새로운 줄 생성
    ### 이 외에도 다양한 메뉴 활용 가능

## Data Processing

### TXT to String

In [1]:
f = open("./data/sample.txt", 'r')
while True:
    line = f.readline()
    if not line: break
    print(line)
    print("<Enter>")
f.close()

자연어처리(NLP)는 사람이 내뱉은 비정형적 자연어를 컴퓨터가 이해할 수 있는 정형적 언어 데이터로 바꾸는 기술이다. 컴퓨터가 문장 의도를 이해하고 말한 사람 의도를 정확히 파악할 수 있도록 해주는 과정이다. 

<Enter>


<Enter>
AI 서비스에서 NLP는 중요한 부분을 차지한다. 컴퓨터가 자연어를 문법상 의미 최소 단위인 형태소로 분해(파싱)해 언어학적 구조를 패턴화, 전체 의미를 파악하도록 해준다. 하나의 품사에 여러 모호성을 해소하는 품사 태깅, 불용어 제거, 기계번역, 대화시스템에 이르기까지 모든 과업을 수행한다. 

<Enter>


<Enter>
최근에는 딥러닝 기반 NLP 연구가 늘고 있다. 단어 단위가 아닌 문장 전체 맥락에서 의미를 추론할 수 있게 됐다. 딥러닝을 적용하기 위해서는 말뭉치(코퍼스, Corpus)라는 학습용 언어 데이터를 필수로 확보해야 한다. 

<Enter>


<Enter>
NLP를 기반으로 한 음성인식 기술은 대용량 음성 데이터를 저장하고 실시간으로 처리 가능한 네트워크와 컴퓨팅 기술로 크게 진화하고 있다. 음성인식 기술 핵심은 상대방과 대화를 계속 이어가는 것이다. 
<Enter>


In [2]:
f = open("./data/sample.txt", 'r')
lines = f.read()
print(lines)
f.close()

자연어처리(NLP)는 사람이 내뱉은 비정형적 자연어를 컴퓨터가 이해할 수 있는 정형적 언어 데이터로 바꾸는 기술이다. 컴퓨터가 문장 의도를 이해하고 말한 사람 의도를 정확히 파악할 수 있도록 해주는 과정이다. 

AI 서비스에서 NLP는 중요한 부분을 차지한다. 컴퓨터가 자연어를 문법상 의미 최소 단위인 형태소로 분해(파싱)해 언어학적 구조를 패턴화, 전체 의미를 파악하도록 해준다. 하나의 품사에 여러 모호성을 해소하는 품사 태깅, 불용어 제거, 기계번역, 대화시스템에 이르기까지 모든 과업을 수행한다. 

최근에는 딥러닝 기반 NLP 연구가 늘고 있다. 단어 단위가 아닌 문장 전체 맥락에서 의미를 추론할 수 있게 됐다. 딥러닝을 적용하기 위해서는 말뭉치(코퍼스, Corpus)라는 학습용 언어 데이터를 필수로 확보해야 한다. 

NLP를 기반으로 한 음성인식 기술은 대용량 음성 데이터를 저장하고 실시간으로 처리 가능한 네트워크와 컴퓨팅 기술로 크게 진화하고 있다. 음성인식 기술 핵심은 상대방과 대화를 계속 이어가는 것이다. 


### EXCEL to Dataframe

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

In [3]:
import pandas as pd

In [4]:
xlsx = pd.read_excel('./data/sample.xlsx', sheet_name=0)

In [5]:
xlsx

이름  국어성적  수학성적
0     강다니엘    10    55
1      강동호    20    60
2      강미나    50    75
3      권현빈    80    90
4      김도연    90    95
5     김사무엘    70    85
6      김세정    60    80
7      김소혜    60    80
8      김청하    30    65
9      노태현    90    95
10    라이관린    30    65
11     박우진    30    65
12     박지훈    70    85
13     배진영   100   100
14     옹성우    90    95
15     유연정    10    55
16     임나영    40    70
17     전소미    30    65
18     정채연    80    90
19     주결경    90    95
20     주학년    10    55
21     최유정    80    90
22  타카다 켄타    20    60
23     하성운    90    95

### CSV to DataFrame

In [6]:
csv = pd.read_csv('./data/sample.csv', header=0, sep=',', encoding='euc-kr')

In [7]:
csv

이름  국어성적  수학성적
0     강다니엘    10    55
1      강동호    60    80
2      강미나     0    50
3      권현빈    20    60
4      김도연    60    80
5     김사무엘    30    65
6      김세정    60    80
7      김소혜    60    80
8      김청하    10    55
9      노태현    40    70
10    라이관린    70    85
11     박우진    10    55
12     박지훈    30    65
13     배진영     0    50
14     옹성우    20    60
15     유연정    60    80
16     임나영    90    95
17     전소미     0    50
18     정채연     0    50
19     주결경    90    95
20     주학년    10    55
21     최유정    90    95
22  타카다 켄타    60    80
23     하성운    10    55

### DataFrame to Numpy

NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

In [8]:
import numpy as np

In [9]:
data = xlsx.values

In [10]:
type(data)

numpy.ndarray

In [11]:
data

array([['강다니엘', 10, 55],
       ['강동호', 20, 60],
       ['강미나', 50, 75],
       ['권현빈', 80, 90],
       ['김도연', 90, 95],
       ['김사무엘', 70, 85],
       ['김세정', 60, 80],
       ['김소혜', 60, 80],
       ['김청하', 30, 65],
       ['노태현', 90, 95],
       ['라이관린', 30, 65],
       ['박우진', 30, 65],
       ['박지훈', 70, 85],
       ['배진영', 100, 100],
       ['옹성우', 90, 95],
       ['유연정', 10, 55],
       ['임나영', 40, 70],
       ['전소미', 30, 65],
       ['정채연', 80, 90],
       ['주결경', 90, 95],
       ['주학년', 10, 55],
       ['최유정', 80, 90],
       ['타카다 켄타', 20, 60],
       ['하성운', 90, 95]], dtype=object)

In [12]:
korean_score = data[:, 1]

In [13]:
print("합 : ", np.sum(korean_score))
print("평균 : ", np.mean(korean_score))
print("표준편차 : ", np.std(korean_score))
print("최대값 : ", np.max(korean_score))

합 :  1330
평균 :  55.416666666666664
표준편차 :  30.135688514155806
최대값 :  100


## Machine Learning Basic

Predict Math score with Korean score.

### Raw Data

In [14]:
data = pd.read_csv('./data/sample.csv', header=0, sep=',', encoding='euc-kr')

In [15]:
data.head()

이름  국어성적  수학성적
0  강다니엘    10    55
1   강동호    60    80
2   강미나     0    50
3   권현빈    20    60
4   김도연    60    80

Drop Names

In [16]:
data = data[['국어성적', '수학성적']].values

In [17]:
data

array([[10, 55],
       [60, 80],
       [ 0, 50],
       [20, 60],
       [60, 80],
       [30, 65],
       [60, 80],
       [60, 80],
       [10, 55],
       [40, 70],
       [70, 85],
       [10, 55],
       [30, 65],
       [ 0, 50],
       [20, 60],
       [60, 80],
       [90, 95],
       [ 0, 50],
       [ 0, 50],
       [90, 95],
       [10, 55],
       [90, 95],
       [60, 80],
       [10, 55]], dtype=int64)

In [18]:
data.shape

(24, 2)

### Split Data: Train data, Validation Data

In [19]:
train_len = 12
train_idxs = np.random.choice(len(data), train_len, replace=False)

In [20]:
train_idxs

array([14, 23, 12, 18, 15,  6,  1,  9,  8, 21, 11, 16])

In [21]:
train_data = data[train_idxs]

In [22]:
train_data

array([[20, 60],
       [10, 55],
       [30, 65],
       [ 0, 50],
       [60, 80],
       [60, 80],
       [60, 80],
       [40, 70],
       [10, 55],
       [90, 95],
       [10, 55],
       [90, 95]], dtype=int64)

In [23]:
val_idxs = [idx for idx in range(len(data)) if idx not in train_idxs]

In [24]:
val_idxs

[0, 2, 3, 4, 5, 7, 10, 13, 17, 19, 20, 22]

In [25]:
val_data = data[val_idxs]

In [26]:
val_data

array([[10, 55],
       [ 0, 50],
       [20, 60],
       [60, 80],
       [30, 65],
       [60, 80],
       [70, 85],
       [ 0, 50],
       [ 0, 50],
       [90, 95],
       [10, 55],
       [60, 80]], dtype=int64)

### Set Models

In [27]:
def f(w, x):
    return w*x

### Set Loss Function

In [28]:
def loss(pre, y):
    return ((pre-y)**2).sum()

### Train and Validate

In [29]:
ws = []
for i in range(5):
    x = train_data[:, 0]
    y = train_data[:, 1]
    
    w = np.random.random()
    pre = f(w, x)
    
    loss_value = loss(pre, x)
    
    # Omit training phase
    # originally, loss_value -> update w
    
    ws.append(w)

In [30]:
for w in ws:
    x = val_data[:, 0]
    y = val_data[:, 1]
    pre = f(w, x)
    loss_value = loss(pre, y)
    print("Loss of %f: %2.2f"%(w, loss_value))

Loss of 0.630381: 25084.46
Loss of 0.733681: 21800.64
Loss of 0.078255: 51791.62
Loss of 0.126865: 48821.06
Loss of 0.377735: 35391.06


### Select Model

In [31]:
w_best = 0.733681

### Test Model

In [32]:
x_test = 80
y_test = 90

In [33]:
pre = f(w_best, x_test)

In [34]:
pre, y_test

(58.69448, 90)

In [35]:
loss(pre, y)

3667.3909896448004